apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
  namespace: oyvindis
  labels:
    app: echo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service
  template:
    metadata:
      labels:
        app: echo-service
    spec:
      containers:
        - name: echo-service
          image: hashicorp/http-echo
          args:
            - "-listen=6789"
            - "-text=banana2"
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: oyvindis
spec:
  type: NodePort
  ports:
    - name: "6789"
      port: 6789
      targetPort: 6789
  selector:
    app: echo
