apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
  namespace: oyvindis
  labels:
    app: echo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service
  template:
    metadata:
      labels:
        app: echo-service
    spec:
      containers:
        - name: echo-service
          image: hashicorp/http-echo
          args:
            - "-text=banana2"
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: oyvindis
spec:
  type: ClusterIP
  ports:
    - port: 5678 # Default port for image
  selector:
    app: echo
