name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy to environment when pull request is created
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME  }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN  }}

      - name: Get Short SHA
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./WebApplication
          platforms: linux/amd64,linux/arm64
          push: true
          tags: oyvindis/http-echo:${{ steps.vars.outputs.sha_short }}

      - name: Set K8s context
        id: setcontext
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.4
        with:
          manifests: ./helm/deployment.yaml
          images: 'hashicorp/http-echo'
          kubectl-version: 'latest'
